source "https://supermarket.chef.io"

cookbook 'ntp'
cookbook 'apt'
cookbook 'rvm', git: 'https://github.com/martinisoft/chef-rvm.git'
cookbook 'nginx', git: 'https://github.com/krukgit/nginx.git'
cookbook 'logrotate'
cookbook 'magic_shell'
